/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Daniel O'Neil (https://sketchfab.com/doneil)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macintosh-classic-1991-3b66e98d137d4a23aaa725ce0a8aec28
Title: Macintosh Classic (1991)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

export const  Computer = (props) => {
  useGLTF.preload('/scene.gltf')

  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mac_Tri_Baked_MacTriBaked_0.geometry}
            // material={materials['Mac.Tri.Baked']}
            position={[-371.19, 0, 0]}
          />
        </group>
      </group>
    </group>
  )
}

export const Scene = () =>{
  console.log('Scene loaded')
return (
  <div id="canvas-container">
          <Canvas>
      <Computer />
    </Canvas>
    </div>
)
}




